Added GitHub actions workflows to preview pull requests.
Creates a GitHub Pages page for the master branch,
as well as a preview for each pull request made.
This is useful for making sure the proposed change
looks right.

Rebased the following commits:

Added start of GitHub Actions PR preview workflow.

Touch .nojekyll files in gh-pages.

Correct syntax error in pr.yaml

Workflow: install libmarkdown2-dev for Ubuntu.

Workflow: give name to artifact upload action

Workflow: don't use heredoc in YAML strings.

Workflow: using wrong variable in pr.yaml

Workflow: use correct URL in pr.yaml

Workflow: use correct URL in pr.yaml

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -3,10 +3,72 @@ on: pull_request
 jobs:
   check_files:
     runs-on: ubuntu-latest
+    env:
+      PAGE_URL: "https://demonstrandum.github.io/based.cooking"
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
+      - name: Set up env
+        run: |
+          PULLNUM=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
+          echo "PULLNUM=$PULLNUM" >> $GITHUB_ENV
       - name: Check files for compliance
-        run: .github/workflows/scripts/check-files.sh
+        run: |
+          PR_FAIL=""
+          if .github/workflows/scripts/check-files.sh > errors.txt; then
+            rm errors.txt  # delete empty file if no errors
+          else
+            PR_FAIL="
+              Your pull-request failed some basic checks:
+
+              \`\`\`
+              $(cat errors.txt)
+              \`\`\`
+            "
+          fi
+
+          echo "PR_FAIL=$PR_FAIL" >> $GITHUB_ENV
+      - name: Build PR preview
+        run: |
+          [ -f errors.txt ] && exit 0
+
+          sudo apt-get update -y
+          sudo apt-get install -y libmarkdown2-dev build-essential
+          REMOTE="./pull-request-$PULLNUM" make deploy
+      - uses: actions/upload-artifact@v1
+        with:
+          name: PrPreview
+          path: ./pull-request-${{ env.PULLNUM }}
+      - name: Commit pr preview to gh-pages
+        run: |
+          [ -f errors.txt ] && exit 0
+
+          git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" --branch gh-pages --single-branch gh-pages
+          cp -r ./pull-request-$PULLNUM ./gh-pages/pull-request-$PULLNUM
+          touch gh-pages/.nojekyll
+          cd gh-pages
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add -A
+          git commit -m "Upload pull-request preview" -a || true
+
+          PR_PREVIEW="A preview of this pull request is available here: \
+                      [Preview for pull request \#$PULLNUM]($PAGE_URL/pull-request-$PULLNUM/index.html)."
+          echo "PR_PREVIEW=$PR_PREVIEW" >> $GITHUB_ENV
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Comment on PR.
+        uses: unsplash/comment-on-pr@v1.3.0
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          msg: "${{ env.PR_FAILED }}${{ env.PR_PREVIEW }}"
+
+
+
 
diff --git a/.github/workflows/upload.yml b/.github/workflows/upload.yml
--- a/.github/workflows/upload.yml
+++ b/.github/workflows/upload.yml
@@ -18,16 +18,45 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    - name: Updating website.
-      uses: appleboy/ssh-action@master
+    - uses: actions/checkout@v2
+    - name: Build page
+      run: |
+        sudo apt-get update -y
+        sudo apt-get install -y libmarkdown2-dev build-essential
+        REMOTE=./deploy make deploy
+    - uses: actions/upload-artifact@v1
       with:
-        host: based.cooking
-        username: based
-        key: ${{ secrets.based_ssh }}
-        passphrase: ${{ secrets.based_ssh_pass }}
-        port: ${{ secrets.based_port }}
-        script: |
-          cd repo
-          git stash
-          git pull --force origin master
-          make deploy
+        name: Deployment
+        path: ./deploy
+    - name: Commit preview to gh-pages
+      run: |
+        git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" --branch gh-pages --single-branch gh-pages
+        cp -r ./deploy/* ./gh-pages
+        touch gh-pages/.nojekyll
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add -A
+        git commit -m "Master branch page preview" -a || true
+        # The above command will fail if no changes were present, so we ignore.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+
+    # Reenable this later on.
+    #- name: Updating website.
+    #  uses: appleboy/ssh-action@master
+    #  with:
+    #    host: based.cooking
+    #    username: based
+    #    key: ${{ secrets.based_ssh }}
+    #    passphrase: ${{ secrets.based_ssh_pass }}
+    #    port: ${{ secrets.based_port }}
+    #    script: |
+    #      cd repo
+    #      git stash
+    #      git pull --force origin master
+    #      make deploy
