Added start of GitHub Actions PR preview workflow.

diff --git a/.github/workflows/upload.yml b/.github/workflows/upload.yml
--- a/.github/workflows/upload.yml
+++ b/.github/workflows/upload.yml
@@ -18,16 +18,41 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    - name: Updating website.
-      uses: appleboy/ssh-action@master
+    - uses: actions/checkout@v2
+    - name: Build page
+      run: |
+        sudo apt-get update -y
+        sudo apt-get install -y build-essential
+        REMOTE=./deploy make deploy
+    - name: Commit preview to gh-pages
+      uses: actions/upload-artifact@v1
+      run: |
+        git clone "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" --branch gh-pages --single-branch gh-pages
+        cp -r ./deploy/* ./gh-pages
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add -A
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
       with:
-        host: based.cooking
-        username: based
-        key: ${{ secrets.based_ssh }}
-        passphrase: ${{ secrets.based_ssh_pass }}
-        port: ${{ secrets.based_port }}
-        script: |
-          cd repo
-          git stash
-          git pull --force origin master
-          make deploy
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+
+    # Reenable this later on.
+    #- name: Updating website.
+    #  uses: appleboy/ssh-action@master
+    #  with:
+    #    host: based.cooking
+    #    username: based
+    #    key: ${{ secrets.based_ssh }}
+    #    passphrase: ${{ secrets.based_ssh_pass }}
+    #    port: ${{ secrets.based_port }}
+    #    script: |
+    #      cd repo
+    #      git stash
+    #      git pull --force origin master
+    #      make deploy
